import os
import gzip

def format_c_array(name, data):
    lines = []
    lines.append(f"const uint32_t {name}_LEN = {len(data)};")
    lines.append(f"const uint8_t {name}[] PROGMEM = {{")
    for i in range(0, len(data), 16):
        chunk = data[i:i+16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        if i + 16 < len(data):
            hex_vals += ","
        lines.append(f"  {hex_vals}")
    lines.append("};\n")
    return "\n".join(lines)

def build_web_assets():
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.abspath(os.path.join(script_dir, ".."))
    data_dir = os.path.join(project_root, "data")
    include_dir = os.path.join(project_root, "include")
    out_header = os.path.join(include_dir, "web_assets_gz.h")

    assets = [
        ("INDEX_HTML_GZ", "index.html"),
        ("STYLE_CSS_GZ", "style.css"),
        ("APP_JS_GZ", "app.js")
    ]

    header_parts = [
        "// Auto-generated by scripts/compress_web.py. DO NOT EDIT MANUALLY.",
        "// Source files in data/ remain uncompressed source assets.",
        "#pragma once",
        "#include <Arduino.h>\n"
    ]

    total_raw = 0
    total_gz = 0

    for c_name, file_name in assets:
        path = os.path.join(data_dir, file_name)
        if not os.path.exists(path):
            raise FileNotFoundError(f"Asset file not found: {path}")

        with open(path, "rb") as f:
            raw_data = f.read()

        gz_data = gzip.compress(raw_data, compresslevel=9)
        total_raw += len(raw_data)
        total_gz += len(gz_data)

        header_parts.append(format_c_array(c_name, gz_data))
        print(f"[compress_web] {file_name}: {len(raw_data)} B -> {len(gz_data)} B ({100*len(gz_data)/len(raw_data):.1f}%)")

    print(f"[compress_web] Total: {total_raw} B -> {total_gz} B ({100*total_gz/total_raw:.1f}%)")

    with open(out_header, "w", encoding="utf-8") as f:
        f.write("\n".join(header_parts))

    print(f"[compress_web] Generated {out_header}")

try:
    from SCons.Script import Import
    Import("env")
    print("[compress_web] Running pre-build compression via PlatformIO...")
    build_web_assets()
except Exception:
    pass

if __name__ == "__main__":
    build_web_assets()
